// Generated by ts-to-zod
import { z } from "zod";
import {
  EntryAction,
  UserAction,
  State,
  ReactionType,
} from "../models/enums";

export const entryActionSchema = z.nativeEnum(EntryAction);

export const userActionSchema = z.nativeEnum(UserAction);

export const stateSchema = z.nativeEnum(State);

export const reactionTypeSchema = z.nativeEnum(ReactionType);
