// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_s78W0VaKQgKWUJ3MDFjq-GdHjWImQTU',
    appId: '1:634063692566:web:32810b1fecd926ba3e6637',
    messagingSenderId: '634063692566',
    projectId: 'e-book-store-4c946',
    authDomain: 'e-book-store-4c946.firebaseapp.com',
    storageBucket: 'e-book-store-4c946.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUjblSpn3WICIeGKSNKY_rYsMou6Vk60Y',
    appId: '1:634063692566:android:6fe86f8c933233353e6637',
    messagingSenderId: '634063692566',
    projectId: 'e-book-store-4c946',
    storageBucket: 'e-book-store-4c946.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJKX6nfjzg2nqTbc63JW60xnIObyIkpLs',
    appId: '1:634063692566:ios:e53806c1a55a67e23e6637',
    messagingSenderId: '634063692566',
    projectId: 'e-book-store-4c946',
    storageBucket: 'e-book-store-4c946.appspot.com',
    iosBundleId: 'com.example.eBookMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJKX6nfjzg2nqTbc63JW60xnIObyIkpLs',
    appId: '1:634063692566:ios:e53806c1a55a67e23e6637',
    messagingSenderId: '634063692566',
    projectId: 'e-book-store-4c946',
    storageBucket: 'e-book-store-4c946.appspot.com',
    iosBundleId: 'com.example.eBookMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_s78W0VaKQgKWUJ3MDFjq-GdHjWImQTU',
    appId: '1:634063692566:web:aa79e419505351bc3e6637',
    messagingSenderId: '634063692566',
    projectId: 'e-book-store-4c946',
    authDomain: 'e-book-store-4c946.firebaseapp.com',
    storageBucket: 'e-book-store-4c946.appspot.com',
  );
}
