// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYdkSkTt1sMSA6GjyaeGe-omC8P6ipQoE',
    appId: '1:743218631806:web:4da8da0cebeaa8a3aa742f',
    messagingSenderId: '743218631806',
    projectId: 'firstflutterapp-a4b9a',
    authDomain: 'firstflutterapp-a4b9a.firebaseapp.com',
    storageBucket: 'firstflutterapp-a4b9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnA3mk2XHGReXTC-R3DPld8DeIHjdxHmA',
    appId: '1:743218631806:android:263c7a36affcb3a3aa742f',
    messagingSenderId: '743218631806',
    projectId: 'firstflutterapp-a4b9a',
    storageBucket: 'firstflutterapp-a4b9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCekv0wvtfId_1gsPB4Bf0GUnnA2L9i3A4',
    appId: '1:743218631806:ios:192d611608206b81aa742f',
    messagingSenderId: '743218631806',
    projectId: 'firstflutterapp-a4b9a',
    storageBucket: 'firstflutterapp-a4b9a.appspot.com',
    iosBundleId: 'mitwpu.edu.in.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCekv0wvtfId_1gsPB4Bf0GUnnA2L9i3A4',
    appId: '1:743218631806:ios:192d611608206b81aa742f',
    messagingSenderId: '743218631806',
    projectId: 'firstflutterapp-a4b9a',
    storageBucket: 'firstflutterapp-a4b9a.appspot.com',
    iosBundleId: 'mitwpu.edu.in.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYdkSkTt1sMSA6GjyaeGe-omC8P6ipQoE',
    appId: '1:743218631806:web:58dbfd20308178deaa742f',
    messagingSenderId: '743218631806',
    projectId: 'firstflutterapp-a4b9a',
    authDomain: 'firstflutterapp-a4b9a.firebaseapp.com',
    storageBucket: 'firstflutterapp-a4b9a.appspot.com',
  );
}
